{
    "config": {
        "abort": {
            "already_configured": "Konto wurde bereits konfiguriert",
            "cannot_connect": "Verbindung fehlgeschlagen",
            "reauth_successful": "Die erneute Authentifizierung war erfolgreich",
            "unknown": "Unerwarteter Fehler"
        },
        "error": {
            "cannot_connect": "Verbindung fehlgeschlagen",
            "invalid_auth": "Ung\u00fcltige Authentifizierung",
            "unknown": "Unerwarteter Fehler"
        },
        "step": {
            "reauth": {
                "data": {
                    "password": "Passwort",
                    "username": "Benutzername"
                }
            },
            "user": {
                "data": {
                    "password": "Passwort",
                    "username": "Benutzername"
                }
            }
        }
    }
}